apollo:
  appid: data-statistics-server
  cluster: dev
  url: "http://localhost:8080"
  namespace: application
  secret: d25eb8f74ff943ada97e7acde26c93ae
naCos:
  address: "127.0.0.1"
  port: 8848
  context-path: "/nacos"
  log-level: debug
  namespace: 7e013039-10f2-467c-aa95-8296042af601
  username: nacos
  password: nacos
  group: DEFAULT_GROUP
  cluster-name:
  data-id: stats-server
